# Matt's MacOSX zshrc

#	general options {{{

HISTFILE=~/.zhistory
HISTSIZE=65535
SAVEHIST=60000
setopt \
	AUTOCD \
	BRACE_CCL \
	EXTENDED_HISTORY \
	HIST_IGNORE_DUPS \
	HIST_IGNORE_SPACE \
	HIST_NO_STORE \
	HIST_SAVE_NO_DUPS \
	HIST_EXPIRE_DUPS_FIRST \
	HIST_FIND_NO_DUPS \
	INC_APPEND_HISTORY \
	MULTIOS \
	PUSHD_SILENT \
    RM_STAR_SILENT
zstyle :compinstall filename '~/.zshrc'
autoload -U compinit tetris zargs zcalc zmv zsh-mime-setup
zmodload zsh/mathfunc
zle -N tetris
FPATH=$(/opt/homebrew/bin/brew --prefix)/share/zsh/site-functions:$FPATH
compinit
zsh-mime-setup
umask 022

#}}}

#	prompt {{{

if [[ -f "/Users/matt/.zprompt" ]]; then
	. /Users/matt/.zprompt
else
	declare PS1="[%n@%B%m%b %1d]%# ";
	autoload promptinit
    #PROMPT='%(?.%F{green}√.%F{red}?%?)%f %B%F{240}%m %1~%f%b %# '
    #PROMPT='%B%F{240}%m %1~%f%b %# '
	promptinit
	prompt adam2
	#prompt elite2
fi
#}}}

#	variables {{{

export GOPATH=$HOME/dev/go
export PATH=/opt/bin:/opt/local/bin:/opt/local/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin:/usr/X11R6/sbin:~/bin:$GOPATH/bin
export LD_LIBRARY_PATH=/usr/lib:/usr/local/lib
export HOSTNAME=`hostname`
export EDITOR=/opt/homebrew/bin/vim
export VISUAL=$EDITOR
export PAGER=`which less`
export LESS=eFRX
export MANPATH=/usr/share/man:/usr/local/share/man
export TMPDIR=/var/tmp
export NOW=`date +%Y%m%d%H%M`
export ZULU=`TZ=Zulu /bin/date +%Y-%m-%dT%H:%m:%SZ`

#}}}

#	aliases {{{

# Qio
alias vq="vi ~/.config/qio/rainbow.toml"
# alias qio="docker run -it --rm gcr.io/craque-420420/rainbow:latest qio --config ./rainbow.toml"

# Dev environment bootstrapping
alias booc="source ~/bin/booc"

# Kubernetes
alias kl="/opt/homebrew/bin/kubectl"
alias kx="/opt/homebrew/bin/kubectx"

# AWS
alias cid="/usr/local/bin/aws sts get-caller-identity"

# Hashicorp
alias tf="/opt/homebrew/bin/terraform"
alias tfvp="tf fmt && tf validate && tf plan"
alias tfls="tf fmt && tf validate && tflint && tfsec && tf plan"
alias terrag='/usr/local/bin/terraform graph | dot -Tsvg > graph.svg && open graph.svg -a /Applications/Net/Google\ Chrome.app'

# git
alias git="/opt/homebrew/bin/hub"
alias gits="git status"
alias gitc="git checkout "
alias gitfp="git fetch && git pull"
alias gitm="git checkout main && git fetch && git pull"
alias gitd="git checkout develop && git fetch && git pull"

# tags
alias ctag="ctags -R --exclude=.github --exclude=.git ."

# alias away macos versions
alias sed='/opt/homebrew/bin/ssed'

# various
alias dv='dirs -v'
alias dvx="dirstack=()"
alias dz='. ~/.zshrc'
alias grep='grep --color=always'
alias gvim='gvim -reverse'
alias h1='h 1'
alias h='history'
alias hgrep='h 1 | grep'
alias history='history -fd'
alias htless="sed -e '/^#.*$/d' -e '/^$/d' < httpd.conf | less"
alias j='jobs'
alias ll='ls -lH'
alias lla='ls -la'
alias lr='ls -ltr'
alias ls='ls -FG'
alias netstat='netstat -f inet'
alias certchk='openssl x509 -noout -text -purpose -in'
alias pi='print $(( pi = 4.0 * atan(1.0) ))'
alias plot='gnuplot'
alias po='popd'
alias pu='pushd'
alias rsynca='rsync -avzP'
alias rsyncan='rsync -avzPn'
alias rxvt='rxvt -bg black -fg moccasin -geometry 100x30 &'
alias idff='icdiff'
alias sdff='sdiff -s'
alias gdff='git-icdiff'
alias ssho='ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
alias sshk='ssh -A -q -p26662 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
alias t='/opt/homebrew/bin/tree -aCI .git' # colored output, show dotfiles, ignore .git
alias t4='/opt/homebrew/bin/tree -L 4 -daCI .git' # level=4, dirs only, colored output, show dotfiles, ignore .git
alias ta='tmux att'
alias mux='tmuxinator'
alias ttcpc='/usr/bin/ttcp -t -s -v -f m -l16384 -n6400 -p10004 '
alias ttcps='/usr/bin/ttcp -r -s -v -f m -l16384 -n6400 -p10004'
alias vi=vim

# suffix aliases
alias -s html=vim
alias -s jinja2=vim

#}}}

#	bindings {{{

# vi key bindings
bindkey -v
# KEYTIMEOUT is in hundredths of a second, switch to command mode in 10ms
export KEYTIMEOUT=1
bindkey -M viins '^?' backward-delete-char
bindkey -M viins '^H' backward-delete-char
bindkey -M viins '^A' beginning-of-line
bindkey -M viins '^E' end-of-line
bindkey -M viins '^P' push-line

# Incremental search is elite!
bindkey -M vicmd "/" history-incremental-search-backward
bindkey -M vicmd "?" history-incremental-search-forward

# Search based on what you typed in already
bindkey -M vicmd "//" history-beginning-search-backward
bindkey -M vicmd "??" history-beginning-search-forward

# other
bindkey TET tetris
bindkey '\e[1~' beginning-of-line
bindkey '\e[3~' delete-char
bindkey '\e[4~' end-of-line
bindkey '^R' history-incremental-search-backward

#}}}

#	completion {{{

zstyle ':completion::complete:*' use-cache 1
zstyle ':completion:*:cd:*' ignored-patterns '(*/)#lost+found'

#}}}

#	terminal {{{

chpwd() {
  [[ -t 1 ]] || return
  case $TERM in
    sun-cmd) print -Pn "\e]l%~\e\\"
      ;;
    *xterm*|gnome-terminal|rxvt|(dt|k|E)term) print -Pn "\e]2;%~\a"
      ;;
  esac
}

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

#}}}

#	miscellaneous {{{
autoload -U +X bashcompinit && bashcompinit

# fuzzy finder
# [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
source <(fzf --zsh)

# Claude Code
export PATH="$HOME/.local/bin:$PATH"

# OpenJDK
export JAVA_HOME="/opt/homebrew/opt/openjdk"
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"

# Node Version Manager
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
#}}}
